-- Master Data Module
DROP TABLE IF EXISTS SUTB_WORKING_DAYS;
DROP TABLE IF EXISTS SUTB_HOLIDAY;

CREATE TABLE SUTB_WORKING_DAYS(
    SUTB_WORKING_DAYS_ID BINARY(16) PRIMARY KEY,
    WEEK_DAY ENUM('MON','TUE','WED','THU','FRI','SAT','SUN') NOT NULL UNIQUE
);

INSERT INTO SUTB_WORKING_DAYS VALUES (UNHEX(REPLACE(UUID(),'-','')),'MON'),
(UNHEX(REPLACE(UUID(),'-','')),'TUE'),
(UNHEX(REPLACE(UUID(),'-','')),'WED'),
(UNHEX(REPLACE(UUID(),'-','')),'THU'),
(UNHEX(REPLACE(UUID(),'-','')),'FRI'),
(UNHEX(REPLACE(UUID(),'-','')),'SAT'),
(UNHEX(REPLACE(UUID(),'-','')),'SUN');

CREATE TABLE SUTB_HOLIDAY(
    SUTB_HOLIDAY_ID BINARY(16) PRIMARY KEY,
    HOLIDAY_ON DATE NOT NULL UNIQUE,
    REASON VARCHAR(256) DEFAULT NULL
);


DELIMITER $$
DROP PROCEDURE IF EXISTS SUPR_WORKING_DAYS_LIST $$
CREATE PROCEDURE SUPR_WORKING_DAYS_LIST (
	OUT pOUT_ACTION_MSG VARCHAR(1000),
	OUT pOUT_ERROR_MSG VARCHAR(1000)
)
SUPR_WORKING_DAYS_LIST:
 BEGIN
	SELECT
		HEX(SUTB_WORKING_DAYS_ID) AS SUTB_WORKING_DAYS_ID,
		WEEK_DAY
	FROM SUTB_WORKING_DAYS;
END
SUPR_WORKING_DAYS_LIST $$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS SUPR_WORKING_DAYS_DELETE $$
CREATE PROCEDURE SUPR_WORKING_DAYS_DELETE (
	IN pIN_SUTB_WORKING_DAYS_ID VARCHAR(32),
	OUT pOUT_ACTION_MSG VARCHAR(1000),
	OUT pOUT_ERROR_MSG VARCHAR(1000)
)
SUPR_WORKING_DAYS_DELETE:
 BEGIN
	DELETE
	FROM SUTB_WORKING_DAYS
	WHERE SUTB_WORKING_DAYS_ID = UNHEX(pIN_SUTB_WORKING_DAYS_ID);
END
SUPR_WORKING_DAYS_DELETE $$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS SUPR_WORKING_DAYS_ADD $$
CREATE PROCEDURE SUPR_WORKING_DAYS_ADD (
	IN pIN_SUTB_WORKING_DAYS_ID VARCHAR(32),
	IN pIN_WEEK_DAY VARCHAR(200),

	OUT pOUT_ACTION_MSG VARCHAR(1000),
	OUT pOUT_ERROR_MSG VARCHAR(1000)
)
SUPR_WORKING_DAYS_ADD:
 BEGIN

	INSERT INTO SUTB_WORKING_DAYS (
		SUTB_WORKING_DAYS_ID, 
		WEEK_DAY
		)
	VALUES (
		UNHEX(pIN_SUTB_WORKING_DAYS_ID),
		pIN_WEEK_DAY
		);
END
SUPR_WORKING_DAYS_ADD $$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS SUPR_WORKING_DAYS_UPDATE $$
CREATE PROCEDURE SUPR_WORKING_DAYS_UPDATE (
	IN pIN_SUTB_WORKING_DAYS_ID VARCHAR(32),
	IN pIN_WEEK_DAY VARCHAR(200),

	OUT pOUT_ACTION_MSG VARCHAR(1000),
	OUT pOUT_ERROR_MSG VARCHAR(1000)
)
SUPR_WORKING_DAYS_UPDATE:
 BEGIN

	UPDATE SUTB_WORKING_DAYS SET
		SUTB_WORKING_DAYS_ID	= 		UNHEX(pIN_SUTB_WORKING_DAYS_ID),
		WEEK_DAY	= 		pIN_WEEK_DAY
		;
END
SUPR_WORKING_DAYS_UPDATE $$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS SUPR_WORKING_DAYS_FIND_BY_ID $$
CREATE PROCEDURE SUPR_WORKING_DAYS_FIND_BY_ID (
	IN pIN_SUTB_WORKING_DAYS_ID VARCHAR(32),
	OUT pOUT_ACTION_MSG VARCHAR(1000),
	OUT pOUT_ERROR_MSG VARCHAR(1000)
)
SUPR_WORKING_DAYS_FIND_BY_ID:
 BEGIN
	SELECT
		HEX(SUTB_WORKING_DAYS_ID) AS SUTB_WORKING_DAYS_ID,
		WEEK_DAY
	FROM SUTB_WORKING_DAYS
	WHERE SUTB_WORKING_DAYS_ID = UNHEX(pIN_SUTB_WORKING_DAYS_ID);
END
SUPR_WORKING_DAYS_FIND_BY_ID $$
DELIMITER ;